### ISSUE TITLE
Support for Up/Down direction [Quest export]

### ISSUE THREAD

**Issue by Selsynn** [henck/trizbort#13]
Like for the gridborder parameter, I would like the up and down direction to be exported to Quest. 
I saw how to specify it in trizbord, but when I exported, the cardinal indication was the thing exported (east / north / west / south)

Like for the other option, I could dig in the code to alter it and push a merge request, if you're interested.

**Comment by henck** [comment]
That looks like a bug, because Trizbort.io does support up/down directions. It's exporting them wrong. You're welcome to contribute (see also issue #12).

**Comment by henck** [comment]
I can see that Trizbort at this point does not export up/down directions to quest. However, this information is available to export. If I could have a sample Quest <asl> that shows what the code should look like, I can add the export.

**Comment by Happy-Ferret** [comment]
I'd be interested in the "secret sauce" to that myself.
I was unable to get "up/down" exports working in general.

Am I right to assume ``CodeGenerator.dirToStr(dir: Direction)`` has to be extended to also accept ``ConnectorType`` for this to work properly?

**Comment by henck** [comment]
@Happy-Ferret Yes. `dirToStr` should probably be moved out of CodeGenerator, since it might be pretty specific per adventuring system. Indeed, the trick is to find the `Direction`, and also look at the `ConnectorType` to see if it's a special case.

Trizbort thinks in terms of 16 directions. The cardinal ones (N,NE,E, ...) and also (NNE, NSE, ...). Any direction may be marked as special. That is, up/down or in/out or even something custom. 

For Tads 3 code generation, the Tads generator should have its own `dirToStr` that performs this check and generate the correct code. For Quest, similar, although I just looked into that and couldn't (quickly) find what Quest expects to find in its XML.

**Comment by henck** [comment]
Up/down and in/out support is now available for all generators. `dirToStr` now takes `ConnectorType` to make this possible.
