### ISSUE TITLE
No way to scroll the map with the mouse wheel

### ISSUE THREAD

**Issue by dfabulich** [henck/trizbort#50]
To reproduce:
Zoom out a few times. Create a room near the edge of the screen. Zoom in a few times, so your room is no longer visible. Scroll with your touch pad or mouse wheel.

Expected:
The canvas should scroll.

Actual:
Scrolling with a touch pad or mouse wheel zooms in and out.

**Comment by dfabulich** [comment]
As an aside, it's a "feature" of the C# Trizbort that you can use the scroll wheel to zoom in and out, but I've never liked that feature. When I want to change the zoom, I want to do it by hand. I would always want the scroll wheel to scroll the map. (At the very least, I'd want the option to disable zooming with the scroll wheel; it messes me up every time I use it.)

**Comment by jeremydouglass** [comment]
Twine uses scrollbars like this. It also restricts the user to a small number of preset zoom levels, rather than offering free zoom (which may be disorienting for beginners).

Another option instead of direct scrollbars is a dragging hand tool, however this is often paired with a HUD box that shows where the current view is on the total canvas, and that can get complicated really quickly.

**Comment by dfabulich** [comment]
While investigating this bug, I realized that it is possible to scroll with the mouse: if you scroll with the right/middle button, the map becomes scrollable. On a macOS touchpad, you can do that by mousing down with two fingers and dragging the map. (But this is not at all discoverable, IMO.)

So I've edited this issue to focus on just the scroll wheel zooming, and filed a separate issue #66 on missing scroll bars.
