### ISSUE TITLE
Alternate "create room in dir" shortcut for users without numeric keypad

### ISSUE THREAD

**Issue by dfabulich** [henck/trizbort#56]
You can use shift-arrow to create a room in the north/south/east/west directions, and you can use PgUp PgDn Home End to create rooms northeast/southeast/northwest/southwest.

My macOS keyboard doesn't have PgUp PgDn Home End keys; I can type Fn-Up for PgUp, Fn-Down for PgDn, Fn-Left for Home and Fn-Right for End.

But Shift-Fn-Right for Southwest is, uh, very confusing.

It would be great if there were an alternate keyboard shortcut for this. I suggest shift-N = north, shift-N-E = northeast, etc.

But even just using the numbers as they appear on a numeric keypad would be an improvement, e.g. shift-8 = north, shift-9 = northeast.

**Comment by jeremydouglass** [comment]
On the one hand, I doubt that a complicated key mapping for ordinal direction shortcuts will be used by many people -- and I doubt that many users will have full numeric keypads on their keyboards.

On the other hand, the nice thing about a full set of mappings is that it makes the whole thing more accessible. Combine that with the ability to toggle through elements, and you start approaching a design where people who can't use a mouse easily or at all could still use this for authoring. That would be pretty great -- especially given the history of IF gaming for people with disabilities.

**Comment by dfabulich** [comment]
> I doubt that a complicated key mapping for ordinal direction shortcuts will be used by many people

Do you think that Shift-N-E for "northeast" is too complicated? I'm imagining:

* Shift-N: North
* Shift-N-E: Northeast
* Shift-E: East
* Shift-S-E: Southeast
* Shift-S: South
* Shift-S-W: Southwest
* Shift-W: West
* Shift-N-W: Northwest
* Shift-U: Up
* Shift-D: Down
* Shift-I: In
* Shift-D: Down

**Comment by jeremydouglass** [comment]
No very strong feelings. If there was a mapping the user could reconfigure it -- or save soft mappings in a cookie, like online games that let you remap controls. My main reason for avoiding mod-plus-two-key-sequence would be the accessibility issue -- and that many users don't understand how to enter (mod+(key1, key2)) before because they have never done it in their life, at best only (mod1+mod2)+key. Also, people may try to type Shift-E-S rather than Shift-S-E.

There is no one best way, unfortunately. For QWERTY users, you could make it the WASD area:

```
Q W E
A   D
Z X C
```

...but that won't work so well for people without qwerty keyboards -- although, like arrow keys, it is spatially intuitive *on* a qwerty keyboard.
