### ISSUE TITLE
Keyboard shortcut in room detail panel to close panel and select the room

### ISSUE THREAD

**Issue by dfabulich** [henck/trizbort#57]
Click on a room. Press Enter to open its detail panel, and type a new name for the room.

There's now no keyboard shortcut to close the detail panel and select the current room. I suggest that Esc could do that (though I see that Esc is currently used for "Unselect All").

This would be useful, together with #54, to allow you to create an entire map with just the keyboard.

**Comment by henck** [comment]
One of the latest updates deletes your selection as soon as you call up the room panel. This is because the system then refreshes the canvas, and all views are deleted and recreated, so the selection cannot persist. It's a new thing @pgsfredda added to speed up drawing for large maps.

I have changed this so that the newly created views also recreate the selection before the panel was opened. In fact, this is now the new behaviour whenever a refresh occurs.

This is a prerequisite for this issue.

**Comment by henck** [comment]
ESC is now bound to both the panels and the editor. When it is pressed when a panel has focus, the panel closes. If the editor canvas has focus, ESC clears the current selection. When a panel closes (through ESC) then the editor canvas gets focus so that it now receives keyboard events.
