### ISSUE TITLE
Change the default map style back to Diagram

### ISSUE THREAD

**Issue by dfabulich** [henck/trizbort#78]
PR #72 changed the default map style to Hand Drawn.

Hand Drawn looks kinda cool, but it's harder to read. I think Diagram is a better default.

**Comment by jeremydouglass** [comment]
I agree that diagram looks very cool on the final output but is tiring to read for more than a few minutes while using the editor. I'd prefer the other default as well -- or make style switching easy in the left-hand menu so it is obvious to first-time users.

(The handdrawn styling also creates a jittering effect when dragging elements around.)

**Comment by henck** [comment]
The changes that added the hand drawn theme introduced various small bugs (notably loading objects from file, which was broken - fixed just now). I have cleaned up and documented the various Model files, which now have lots of accessors that help detect whether a model changed so that the editor knows when to redraw instead of constantly, which is a good thing for large maps. 

@pgsfredda chose to add the hand-drawn style as a built-in theme. I don't agree with this, as I think it should be a render setting that you can actually turn on/off in your own theme, rather than hiding it in a theme you cannot change. I need to figure out where the hand-drawn setting is, and move it to render settings.

Also, the hand-drawn style creates a jittering effect as it redraws lines. It does this, I presume, because it uses a new random seed for every line it draws. It would be better if the random seed were saved with the line somehow (or with the View) so that it always draws the same lines so you wouldn't see any jittering. I'll make an issue of that.
